[package]
name = "lsm"
version = "0.1.0"
authors = ["Marwan Liani <marwan.liani@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
termion = "*"